language: java

addons:
   sonarcloud:
     organization: "remeic"
     token: ${SONAR_TOKEN}

matrix:
   include:
      # always build this environment
      - jdk: openjdk8
      # only on PR
      - jdk: openjdk9
        if: type IN (pull_request)     

services:
   - docker
   - xvfb
# skip installation step
install: true


cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache

script:
   - ./mvnw clean verify -Pjacoco sonar:sonar