language: java

addons:
  sonarcloud:
    organization: "remeic"
    token: ${SONAR_TOKEN}

git:
  depth: false

matrix:
  include:
    - jdk: openjdk8
      if: type IN (push) AND type NOT IN (pull_request)
      env: MAVEN_ARGS="-Pjacoco coveralls:report sonar:sonar"
    # only on PR
    - jdk: openjdk8
      if: type IN (pull_request)
      env: MAVEN_ARGS="-Pjacoco,it coveralls:report sonar:sonar"
    - jdk: openjdk8
      if: type IN (pull_request)
      env: MAVEN_ARGS="-Ppit"

services:
  - docker
  - xvfb

# skip installation step
install: true

env: DISPLAY=:99.0

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

before_script:
  - "Xvfb :99 &"
  - "export DISPLAY=:99"

script:
  - ./mvnw clean verify $MAVEN_ARGS
