language: java

addons:
   sonarcloud:
     organization: "remeic"
     token: ${SONAR_TOKEN}

matrix:
   include:
      # always build this environment
      - jdk: openjdk8
        env: MAVEN_ARGS="-Pjacoco coveralls:report sonar:sonar"
      # only on PR
      - jdk: openjdk8
        if: type IN (pull_request)
        env: MAVEN_ARGS="-Pjacoco coveralls:report sonar:sonar"

services:
   - docker
   - xvfb
# skip installation step
install: true


cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache

script:
   - ./mvnw clean verify $MAVEN_ARGS