language: java

matrix:
   include:
      # always build this environment
      - jdk: openjdk8
      # only on PR
      - jdk: openjdk9
        if: type IN (pull_request)
      # only on PR or after merging a PR
      - os: osx
        osx_image: xcode10.1
        if: type IN (pull_request) OR commit_message =~ /^Merge pull request/

# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2

script:
   - mvn -f ./pom.xml clean verify 